# Generated by Django 4.0.1 on 2022-01-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
