# Generated by Django 4.0.1 on 2022-01-10 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expensesapp', '0002_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_datetime', models.DateTimeField()),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('vat', models.FloatField()),
                ('description', models.TextField(max_length=200)),
                ('category', models.CharField(choices=[('ML', 'Meal'), ('TI', 'Taxi')], max_length=2)),
                ('date_incurred', models.DateField()),
                ('claim', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='expensesapp.claim')),
            ],
        ),
    ]
