# Generated by Django 4.0.1 on 2022-01-13 16:32

from django.db import migrations, models
import expensesapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0002_alter_claim_description'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', expensesapp.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
