# Generated by Django 4.0.1 on 2022-01-10 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
