# Generated by Django 4.0.1 on 2022-01-13 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0004_claim_reference_alter_claim_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
