# Generated by Django 4.0.1 on 2022-01-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0005_alter_claim_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
