# Generated by Django 4.0.1 on 2022-04-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0006_alter_user_default_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='vat_name',
            field=models.CharField(choices=[('1', 'VAT'), ('2', 'Sales tax')], default='1', max_length=1),
            preserve_default=False,
        ),
    ]
