# Generated by Django 4.0.1 on 2022-04-12 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0007_currency_vat_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='vat_name',
            field=models.CharField(choices=[('1', 'VAT'), ('2', 'Sales Tax')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='default_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expensesapp.currency'),
        ),
    ]
