# Generated by Django 4.0.1 on 2022-01-14 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0008_alter_claim_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expensesapp.claim'),
        ),
    ]
