# Generated by Django 4.0.1 on 2022-04-12 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0009_alter_user_default_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expensesapp.currency'),
        ),
    ]
