# Generated by Django 4.0.1 on 2022-01-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0009_alter_receipt_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PE', 'Pending Authorisation'), ('AU', 'Authorised')], default='DR', max_length=2),
            preserve_default=False,
        ),
    ]
