# Generated by Django 4.0.1 on 2022-04-12 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0010_alter_user_default_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='default_currency',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='expensesapp.currency'),
        ),
    ]
