# Generated by Django 4.0.1 on 2022-01-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0010_claim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('DR', 'Draft'), ('PE', 'Pending'), ('SE', 'Sent')], max_length=2),
        ),
    ]
