# Generated by Django 4.0.1 on 2022-04-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0011_alter_user_default_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='submission_datetime',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
