# Generated by Django 4.0.1 on 2022-04-15 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0017_alter_user_primary_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('1', 'Draft'), ('2', 'Pending'), ('3', 'Sent'), ('4', 'Accepted'), ('5', 'Rejected')], max_length=1),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='expensesapp.claim'),
        ),
    ]
