# Generated by Django 4.0.1 on 2022-04-16 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0018_alter_claim_owner_alter_claim_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('1', 'Draft'), ('2', 'Pending'), ('3', 'Sent'), ('4', 'Accepted')], max_length=1),
        ),
    ]
