# Generated by Django 4.0.1 on 2022-04-17 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0022_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='action_desc',
            field=models.CharField(default='abc', max_length=50),
            preserve_default=False,
        ),
    ]
