# Generated by Django 4.0.1 on 2022-04-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0023_feedback_action_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='action_desc',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='comment',
            field=models.CharField(max_length=200),
        ),
    ]
