# Generated by Django 4.0.1 on 2022-04-17 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0027_rename_approval_author_claim_approval_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='back_url',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
