# Generated by Django 4.0.1 on 2022-04-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0029_remove_claim_back_url_user_back_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='back_url',
            field=models.CharField(blank=True, default=None, max_length=60, null=True),
        ),
    ]
