# Generated by Django 4.0.1 on 2022-04-18 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0030_alter_user_back_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
