# Generated by Django 4.0.1 on 2022-04-18 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0031_receipt_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
